import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Container, Center, Input, Wrap, WrapItem } from "@chakra-ui/react";
import CartasNFT from "./Cartas/Cartas";


export default function Home() {
  return (
    <>
      <Head>
        <title>Filtro de Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.lg">

        <CartasNFT />

       
      </Container>
    </>
  );
}
